### ISSUE TITLE
@mentioned new user and didn't prompt for email? 

### ISSUE THREAD

**Issue by jeffdomke** [blockstack-radiks/banter#49]
![Screen Shot 2019-03-05 at 7:01 PM](http://marker.screenshots.prod.s3.amazonaws.com/863ba9e89b5a4327b1c1d7a124505cf9-1551812489666.png)

What does this mean? They are already in the DB? 

https://staging.banter.pub/

---
### More Info

**Source URL**: [https://staging.banter.pub/](https://staging.banter.pub/)

**Comment by jeffdomke** [comment]
![screen shot 2019-03-05 at 2 45 53 pm](https://user-images.githubusercontent.com/767828/53832932-66bdde00-3f55-11e9-8665-083574974e72.png)

**Comment by jeffdomke** [comment]
Is this just the plaintext with the link or is something messed up here?

**Comment by jeffdomke** [comment]
@hstove think what is happening is that I previously invited this ID while testing. So they are invited per Radiks but if I mention them nothing happens? Wonder if we can have an exception for this? 

Can you please check on: `@vader.id.blockstack` on stage?

**Comment by hstove** [comment]
This is likely due to the websocket closing. The fix for this is either:

- Accept breakage when they see the 'restart the app' notification
- Update the websocket logic to try and re-connect
- Update the 'new message created' logic to not use the websocket (requires some refactoring, but probably a good idea regardless)

**Comment by jeffdomke** [comment]
Will close for now, we can readdress if we see it again.
